name: diagnostic_lab_app
description: "Diagnostic Lab MVP Starter"
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.0.0
  firebase_auth: ^4.0.0
  cloud_firestore: ^4.0.0
  firebase_storage: ^11.0.0
  google_maps_flutter: ^2.2.0
  geolocator: ^9.0.0
  flutter_dotenv: ^6.0.0
  http: ^0.13.0
  url_launcher: ^6.0.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
